CATEGORY = [
    "Áo",
    "Áo khoác",
    "Áo dài",
    "Áo thun",
    "Áo sơ mi",
    "Áo croptop",
    "Áo len",
    "Áo hoodie",
    "Áo sweater",
    "Áo vest",
    "Áo blazer",
    "Áo phao",
    "Áo dạ",
    "Áo măng tô"
    "Set bộ",
    "Set bộ công sở",
    "Quần",
    "Quần jeans",
    "Quần dài",
    "Quần lửng",
    "Quần short",
    "Quần khaki"
    "Chân váy",
    "Chân váy bút chì",
    "Chân váy chữ A",
    "Chân váy jeans",
    "Váy",
    "Váy đầm nữ",
    "Đầm công sở",
    "Đầm thun",
    "Đầm maxi",
    "Khác"
]
